<h1>
    Cadastro de Cliente
</h1>
<a href="<?=$this->url('clientes', ['action'=>'add'] );?>">
    Novo Cliente
</a>

<table class="table">
    <thead>
    <tr>
        <th>Foto</th>
        <th>Nome</th>
        <th>Email</th>
        <th>Telefone</th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    <?php foreach($clientes as $cliente) : ?>
    <tr>
        <td><img width="100" src="/img/cliente/<?= $this->escapeHtml($cliente->foto) ?>"/></td>
        <td><?= $this->escapeHtml($cliente->nome) ?></td>
        <td><?= $this->escapeHtml($cliente->email) ?></td>
        <td><?= $this->escapeHtml($cliente->telefone) ?></td>
        <td>
            <a href="<?=$this->url('clientes', ['action'=>'edit', 'idclientes'=>$cliente->idclientes] );?>">
                Editar
            </a>
            <a href="<?=$this->url('clientes', ['action'=>'delete', 'idclientes'=>$cliente->idclientes] );?>">
                Excluir
            </a>
        </td>
    </tr>
    <?php endforeach; ?>
    </tbody>
</table>